### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by engcom-Bravo** [AdobeDocs/commerce-operations.en#102]
## Description

This is about the default setting to have changed from being [enabled in 2.4.5 and earlier](https://github.com/magento/magento2/blob/2.4.5/app/code/Magento/CatalogUrlRewrite/etc/config.xml#L12) to [disabled in 2.4.6 and later](https://github.com/magento/magento2/blob/2.4.6/app/code/Magento/CatalogUrlRewrite/etc/config.xml#L12) .
Based on the commit message in https://github.com/magento/magento2/commit/e2ab9c01f1fda7bf62aabb1702531c9daeb16418, it looks like this was done for improved performance, which I agree with, it's much faster to have this setting disabled.

So, in my opinion, this is more a bug in the documentation, where it wasn't specified in the release notes.It is better get it added to the release notes for Magento 2.4.6

**Comment by hostep** [comment]
Note that this is a copy paste of [my comment here](https://github.com/magento/magento2/issues/37772#issuecomment-1643808398)

**Comment by jeff-matthews** [comment]
@hostep, I think that we documented this in the 2.4.6 [backward-incompatible changes](https://developer.adobe.com/commerce/php/development/backward-incompatible-changes/highlights/#new-default-value-for-automatic-redirects). Will you please confirm?

**Comment by hostep** [comment]
Ah your absolutely correct!
I only looked into the release notes, failed to look into the BiC list.

I believe you can close this ticket here, nothing needs to be done.

Thanks for the feedback!

**Comment by jeff-matthews** [comment]
No problem! Thanks for checking in 😄
