### ISSUE TITLE
Mismatching versions & instructions

### ISSUE THREAD

**Issue by BarnyShergold** [AdobeDocs/commerce-operations.en#103]
Issue in ./help/upgrade/implementation/perform-upgrade.md

This page should be overhauled. It refers to update methods going back to 2.4.1 and also examples and commands have mismatched versions

**Example - Minor release**
Text refers to 2.4.3 :
`Minor releases contain new features, quality fixes, and security fixes. Use Composer to specify a minor release. For example, to specify the Magento Open Source 2.4.3 metapackage:`

Instruction refers to 2.4.0
composer require-commerce magento/product-community-edition 2.4.0 --no-update

**Example - Quality patch**
Text refers to 2.4.1 :
`Quality patches primarily contain functional and security fixes. However, they can sometimes contain new, backward-compatible features. Use Composer to download a quality patch. For example, to specify the Magento Open Source 2.4.1 metapackage:`

Instruction refers to 2.4.3
`composer require-commerce magento/product-community-edition 2.4.3 --no-update`

And so on. ALL examples should be updated to refer to a SINGLE commerce version. EG 2.4.6 (as latest)

Also 'composer require-commerce' method throws an error when executed on Composer 2.
```
Deprecation Notice: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /private/var/www/abb-motions-ecommerce-frankfurt/vendor/magento/composer-root-update-plugin/Utils/PackageUtils.php:128
Deprecation Notice: VersionSelector::findBestCandidate with ignored platform reqs as bool|array is deprecated since Composer 2.2, use an instance of PlatformRequirementFilterInterface instead. in phar:///usr/local/Cellar/composer/2.4.4/bin/composer/src/Composer/Package/Version/VersionSelector.php:80
```

Normally I use 'composer update magento/product-enterprise-edition' version

Finally, updating on Cloud is slightly different too. This should be mentioned.

**Comment by hostep** [comment]
> Also 'composer require-commerce' method throws an error when executed on Composer 2.
> 
> Deprecation Notice: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /private/var/www/abb-motions-ecommerce-frankfurt/vendor/magento/composer-root-update-plugin/Utils/PackageUtils.php:128


That error you're encountering has already been fixed in https://github.com/magento/composer-root-update-plugin/commit/dcbfe8b121b7767443c33289e0ab0173117771bb

However, 11 months later, they still forgot to release that fix in a stable new version ...
I'll ask Stanislav on Slack to take a look.

_Update_, looks like this was already noticed this some months ago over here: https://github.com/magento/composer-root-update-plugin/issues/36

**Comment by jeff-matthews** [comment]
@adobe export issue to Jira project COMDOX as Story

**Comment by jeff-matthews** [comment]
@BarnyShergold
 
I addressed the majority of your comments in https://github.com/AdobeDocs/commerce-operations.en/commit/f87eadce28977cd5952626ba1801be64d5802cb3.

The issue with the Composer plugin command appears to be a code issue. Please feel free to open a new issue (or PR) to suggest additional guidance.
