### ISSUE TITLE
What is this? Where to download the copy file, people ?!?!?!?!?!?!!!!

### ISSUE THREAD

**Issue by Aljumiai** [AdobeDocs/commerce-operations.en#114]
Issue in ./help/release/release-notes/open-source/2-4-6.md

**Comment by jfrontain** [comment]
Hello @aljumiai, the exact source of your frustration with the Magento Open Source 2.4.6 release notes isn’t clear to me. Is the issue that you don’t see a link that takes you directly to the 2.4.6 open source package? Installing and deploying Magento Open Source is a multi-phase procedure, and to carefully prepare merchants, we encourage them to first read the system requirements for running Magento Open Source so they can best prepare their environment before deployment. We also provide a link to the [Quick start on-premises installation](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/composer.html), which describes the installation process and instructions for accessing the software packages. 

If this is not the source of your frustration, please add a note to this issue so I can respond more helpfully. I will close this issue in three days if you do not respond.

**Comment by jfrontain** [comment]
Closing due to lack of response from issue reporter. @Aljumiai, please re-open with an informative message as needed.
