### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by fauzie** [AdobeDocs/commerce-operations.en#123]
Issue in ./help/configuration/cli/start-message-queues.md
Link `queue:consumers:start` is 404 at the end of page on phrase:
See [queue:consumers:start](https://devdocs.magento.com/guides/v2.4/reference/cli/magento-commerce.html#queueconsumersstart) in the Commerce section of the Command-line tools reference for details about the command options, parameters, and values.

**Comment by jeff-matthews** [comment]
Thanks for the report @fauzie! This [commit](https://github.com/AdobeDocs/commerce-operations.en/commit/2b93c533c96bbcee96b6d0040cd7179f3a50b4ff) _should_ fix it. I'll confirm after deployment and reopen this issue if not.

**Comment by jeff-matthews** [comment]
Confirmed that the fix worked
