### ISSUE TITLE
Remove conflicting statements in High Throughput Processing

### ISSUE THREAD

**Issue by stephen-garner-adobe** [AdobeDocs/commerce-operations.en#18]
There's a conflicting statement in this document:

_'All features work independently. You can use all the features simultaneously or enable and disable features in any combination.'_

However, under 'Negotiable Quote Async Order', there is a dependancy on two items to be used together, as stated: 

_The Negotiable Quote Async Order B2B module enables you to save order items asynchronously for the NegotiableQuote functionality. You must have AsyncOrder and NegotiableQuote enabled._

The dependancy on having Negotiable Quote Order Async is both Async Order, and Negotiable Quotes.

Suggested remediation of the statement:
I'd suggest removing _'All features work independently. You can use all the features simultaneously or enable and disable features in any combination.'_ altogether, and have the documentation speak for itself as the statement of using all independently isn't valid, and is dependant on another condition being enabled before Negotiable Quote Order Async can be used.

Issue in ./help/performance/high-throughput-order-processing.md

**Comment by hguthrie** [comment]
Thank you for pointing this out. I see where the confusion is now. I will post a fix soon that makes a more clear distinction of the three features that work independently. It should be the following:

- AsyncOrder is DISABLED
- Switchable Inventory Check on Quote Load is ENABLED
- Deferred Total Calculation is DISABLED
