### ISSUE TITLE
No link provided.

### ISSUE THREAD

**Issue by agilecodex** [AdobeDocs/commerce-operations.en#2]
Issue in ./help/commerce-at-scale/caching.md

The last line "An example manual cache clear operation for AEM and Adobe Commerce is shown here." of https://experienceleague.adobe.com/docs/commerce-operations/deliver-commerce-at-scale/caching.html?lang=en has no any link for "shown here".

**Comment by jeff-matthews** [comment]
Thanks for the report @agilecodex! I'm looking into it.

**Comment by jeff-matthews** [comment]
The following links need to be added:

- Clear the Adobe Commerce cache: https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cache.html#config-cli-subcommands-cache-clean
- Clear AEM Dispatcher cache: https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/page-invalidate.html?lang=en

I suggest removing the last sentence and adding links to the first sentence:

> Even if content is updated and needing to be made live within the caching TTL, it is, in most cases, possible to manually clear the caches for the [AEM dispatcher](https://experienceleague.adobe.com/docs/experience-manager-dispatcher/using/configuring/page-invalidate.html?lang=en) and [Adobe Commerce](https://devdocs.magento.com/guides/v2.4/config-guide/cli/config-cli-subcommands-cache.html#config-cli-subcommands-cache-clean) cache selectively for that content, meaning that urgent changes will be reflected immediately.

**Comment by jeff-matthews** [comment]
@agilecodex, would you be willing to open a pull request to update the docs?

**Comment by agilecodex** [comment]
@jeff-matthews If you want, I would like to open a pull request to update the docs.

**Comment by jeff-matthews** [comment]
@agilecodex, great! Just click the **Edit this page** icon to go to the page in this repo, then click edit again to start making changes.

![Screen Shot 2022-01-27 at 9 37 19 AM](https://user-images.githubusercontent.com/13662379/151391789-d3a8c260-50ea-4905-ba27-ad3454dba09d.png)

You can also refer to the [authoring guide](https://experienceleague.adobe.com/docs/authoring-guide-exl/using/editing/git-workflow-infrequent-user.html?lang=en#making-direct-edits) for more info, but please ignore the first bullet that mentions going to `git.corp.adobe.com`. That only applies to Adobe employees and needs to be clarified in the guide.

**Comment by agilecodex** [comment]
Yes, I've updated it according to your suggestions.

**Comment by jeff-matthews** [comment]
Please add a link to your pull request (PR) here in the comments so that the issue and PR are connected.

**Comment by jeff-matthews** [comment]
I see your commit in your fork, but you still need to create the PR.

1. Click your [commit](https://github.com/agilecodex/commerce-operations.en/commit/87e379aff4ec57f15ce914a13b4e9bc2769e6d1c)
2. Click **Pull Requests**
3. Click **New Pull Request**
4. In the head repository on the right, click the drop down and select your branch that has your commit (patch-1).

![Screen Shot 2022-01-27 at 10 20 48 AM](https://user-images.githubusercontent.com/13662379/151399741-ced472be-c8b2-4ffd-bf2f-f17e85a46d45.png)

5. Click **Create pull request**.

**Comment by hguthrie** [comment]
Closing issue because it looks like the update was merged.
