### ISSUE TITLE
Incorrect export DATA_CONVERTER_BATCH_SIZE command 

### ISSUE THREAD

**Issue by tom-knight** [AdobeDocs/commerce-operations.en#26]
## Description

The current [upgrade documentation](https://github.com/AdobeDocs/commerce-operations.en/blob/main/help/upgrade/prepare/prerequisites.md) says to run:

```bash
export DATA_CONVERTER_BATCH_SIZE 100000
```

before running the upgrade. Running this in bash  5.1.16(1)-release gives the following error:

```bash
bash: export: `100000': not a valid identifier
```

The correct command should be:

```bash
export DATA_CONVERTER_BATCH_SIZE=100000
```

### Steps to reproduce

Run command:

```bash
export DATA_CONVERTER_BATCH_SIZE 100000
```

## Expected result

You shouldn't get any errors from bash and the environment variable is set:

```bash
echo $DATA_CONVERTER_BATCH_SIZE
```

## Possible solutions

Documentation updated to correct command:

```bash
export DATA_CONVERTER_BATCH_SIZE=100000
```

**Comment by dshevtsov** [comment]
@tom-knight, good catch! Thank you for your feedback. I have opened an internal PR to fix this.
