### ISSUE TITLE
Azure availability map may be incorrect

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/commerce-operations.en#32]
Issue in ./help/implementation-playbook/infrastructure/cloud/regions.md
https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/infrastructure/cloud/regions.html?lang=en#azure-regions

The Azure availability map is different (showing more availability zones) to the one provided on Field Readiness https://fieldreadiness-adobe.highspot.com/items/5f1885ada4dfa07661acaa35?lfrm=srp.5#3 

Jay Chaudhury advised that FR is the accurate source which he updates, so the public page may be inaccurate and need a revision.

It is also ambiguous what 'potential availability zones' means, or the 'local' zone marked on the AWS map means - will be worth updating to a clearer statement

**Comment by jeff-matthews** [comment]
@adobe export issue to Jira project COMDOX as Story

**Comment by jeff-matthews** [comment]
Updated in https://github.com/AdobeDocs/commerce-operations.en/commit/5889b5757d02823750c92c5ef561e5f1aa1ad67f. Will be deployed to production shortly.
