### ISSUE TITLE
Incorrect URL for account login

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-operations.en#34]
Issue in ./help/tools/site-wide-analysis-tool/installation.md

1. Under the Commerce Services Connector heading:

Log into ``accounts.magento.com`` - the URL should be **account.magento.com** (without the S)

2. I also suggest adding a hint about what you should do if you are unable to log into the account: 
[Unable to log in to Adobe Commerce support or cloud account](https://support.magento.com/hc/en-us/articles/8472095067021)

**Comment by meker12** [comment]
Published update to address this issue. Update is available in Experience Leagure: [Sitewide Analysis Tool - Installation - Commerce Services Connector. ](https://experienceleague.adobe.com/docs/commerce-operations/tools/site-wide-analysis-tool/installation.html#commerce-services-connector)
