### ISSUE TITLE
user feedback on the benchmark figures

### ISSUE THREAD

**Issue by yanlicao** [AdobeDocs/commerce-operations.en#38]
Issue in ./help/implementation-playbook/infrastructure/performance/benchmarks.md

Dear team
We received this comment at https://github.com/AdobeDocs/commerce-operations.fr-FR/issues/2

it says the figures are not correct, should be 2M page views per hours and 208k orders per hours 

Can you please verify?
Please also feel free to reply directly in the fr-FR issue if that is more convenient for you.

**Comment by jeff-matthews** [comment]
Thanks @yanlicao. I'm attempting to verify the info with Product Management.

**Comment by jeff-matthews** [comment]
Verified with Product Manager and updated the source: https://github.com/AdobeDocs/commerce-operations.en/commit/f5c890e9c714782d92db52b0d62d06118dcdb180.

Updates will be published today during the next deployment window.
