### ISSUE TITLE
Footer year is still 2021

### ISSUE THREAD

**Issue by agilecodex** [AdobeDocs/commerce-operations.en#4]
## Topic Link

https://experienceleague.adobe.com/docs/

## Description

Footers of every page of https://experienceleague.adobe.com/docs/ have "Copyright © 2021 Adobe. All Rights Reserved."

## Possible solutions

Change "2021" to "2022"

**Comment by jeff-matthews** [comment]
This looks like a bug because the main experienceleague.adobe.com home page shows the correct date in the footer (2022). As indicated in the issue description, only doc pages seem to contain the incorrect date (2021).

**Comment by bbringhu** [comment]
This should be fixed soon. The fix will trigger the year to be updated automatically every January, as it is in the rest of EXL.

**Comment by jeff-matthews** [comment]
This is fixed. The footer now uses a dynamic date. Thanks for the report @agilecodex!
