### ISSUE TITLE
What about the use of shared catalog on the calc of the "Effective SKU" numer

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-operations.en#49]
Issue in [./help/implementation-playbook/best-practices/planning/product-sku-limits.md](https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/best-practices/planning/product-sku-limits.html)

Please, it would be good to clarify how the uses of shared catalog influence the value of the "Effective SKU" numer

**Comment by danidelcar** [comment]
we're working on it

**Comment by danidelcar** [comment]
Hi @joaquin-becerra , we are looking to update this page with information that helps clarify how the uses of shared catalog could affect the value of the effective SKU number

**Comment by joaquin-becerra** [comment]
Great! thanks

**Comment by danidelcar** [comment]
we just merged a PR that updates the section. Should be available during today @joaquin-becerra , thanks!

**Comment by danidelcar** [comment]
Page updated, closing issue as completed
