### ISSUE TITLE
Search Engine user guide link goes to a 404 page

### ISSUE THREAD

**Issue by briangmoore77** [AdobeDocs/commerce-operations.en#52]
Issue in ./help/configuration/search/configure-search-engine.md

In this sentence "For additional details about configuring your search engine, see the [User Guide](https://docs.magento.com/user-guide/catalog/search-elasticsearch.html)." That link goes to a 404 page.

**Comment by jeff-matthews** [comment]
Thanks for the report @briangmoore77. I think this is the page the link should point to: https://experienceleague.adobe.com/docs/commerce-admin/catalog/catalog/search/search-configuration.html

**Comment by colindaviddick** [comment]
I'd have a look at this if it's still available?

**Comment by jeff-matthews** [comment]
@colindaviddick, it's available. Please feel free to open a pull request!

**Comment by colindaviddick** [comment]
Hi, I've signed the Adobe CLA but I'm getting an error: **Add pull requests / Add to Commerce project (pull_request_target)**

Is this something I can fix? I've had a look but I'm not really seeing any way to resolve it.

**Comment by jeff-matthews** [comment]
Thanks for the PR @colindaviddick!

You can ignore that error. It's related to some automation that we're experimenting with and won't affect our ability to process your PR.

I'll finish processing your contribution first thing tomorrow.
