### ISSUE TITLE
Error on sql query

### ISSUE THREAD

**Issue by joaquin-becerra** [AdobeDocs/commerce-operations.en#68]
Issue in ./help/implementation-playbook/best-practices/maintenance/commerce-235-upgrade-prerequisites-mariadb.md

Where it says:

`SELECT table_name, row_format FROM information_schema.tables WHERE table_schema=DATABASE() and row_format 'Compact';
`
should say:
`
SELECT table_name, row_format FROM information_schema.tables WHERE table_schema=DATABASE() and row_format  = 'Compact';`

(note the '=' added)

Regards

**Comment by dshevtsov** [comment]
@AmyJZhao, the GJSS bot didn't work in some reason. It's mapped [here](https://github.com/adobe/gjss-lib/blob/main/server/model/jira/project-config.js#L4158-L4159) and [here](https://github.com/adobe/gjss-lib/blob/main/server/model/github/config/export-config.js#L52).
