### ISSUE TITLE
Varnish 7.0 already EOL

### ISSUE THREAD

**Issue by lopf** [AdobeDocs/commerce-operations.en#75]
## Topic Link

https://github.com/AdobeDocs/commerce-operations.en/blob/main/help/_includes/templated/system-requirements-table.md

## Description

Varnish 7.0 is listed as the latest tested Varnish version for Magento >= 2.4.4 but Varnish 7.0 is already EOL. This leads to people wanting to install Varnish in a version which is already not supported anymore.

This is a followup of magento/magento2#35536 which documents that the admin backend doesn't even provide the Varnish 7.0 configuration template.

## Possible solutions

Stick to a Varnish LTS release (currently 6.0) until a feature of a newer version is required.

**Comment by jeff-matthews** [comment]
Thanks for the report, but this isn't a docs issue.
