### ISSUE TITLE
Emphasize that Elasticsearch 7.16 and newer is not supported on Cloud

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-operations.en#79]
Issue in ./help/installation/system-requirements.md

There is some confusion regarding the system requirements for Elasticsearch on Cloud vs. Open Search - this page implies that 7.16 and 7.17 can be also used on Cloud, but that is not the reality.

The granular requirement for Cloud is that Open Search must be used/installed in place of Elasticsearch 7.16+

More information: https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/service/opensearch.html?lang=en

**Comment by jeff-matthews** [comment]
Thanks @ak77-prime. We've heard similar feedback before. We have an "important" note below the table that advises users about the potential differences between on-prem and cloud. We could call out search engine support as an example, but not exhaustive. I think there may be some other differences. If not now, there could be in the future.

Maybe we should move it above the table.

<img width="1080" alt="Screenshot 2023-01-26 at 3 14 06 PM" src="https://user-images.githubusercontent.com/13662379/214952081-d9c3d1f6-fcfe-4ac1-ab05-46f2850f4e34.png">

**Comment by jeff-matthews** [comment]
We recently consolidated cloud and on-prem system requirements using a tabbed view: https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

The lead-in paragraph also explicitly states:

> For example, Elasticsearch 7.17 is supported for Commerce 2.4.4 for on-premise deployments, but OpenSearch 1.2 is supported for Commerce 2.4.4 on Cloud infrastructure.
