### ISSUE TITLE
Broken links in Search engine overview page

### ISSUE THREAD

**Issue by igrybkov** [AdobeDocs/commerce-operations.en#80]
Issue in [./help/configuration/search/overview-search.md](https://github.com/AdobeDocs/commerce-operations.en/blob/main/help/configuration/search/overview-search.md)

Hello,

Some links in this file (first 4 in the list) are broken and don't work in the web version: https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/search/overview-search.html?lang=en

**Comment by jeff-matthews** [comment]
Thanks for letting us know @igrybkov. It's because those links use link definitions for relative linking, which the Experience League authoring platform does not support. I'll move the links inline, which should fix it.

**Comment by jeff-matthews** [comment]
Fixed in https://github.com/AdobeDocs/commerce-operations.en/commit/72dadb5e92df0d94252aca8f30f27210234e5521. 

Will be deployed in today's next scheduled production run (~2hours).
