### ISSUE TITLE
Convert the run-on sentence in the headings of each section to include the original links provided in New Relic

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-operations.en#81]
Issue in ./help/tools/observation-for-adobe-commerce/bots.md

The heading of each section that's copied from New Relic contains links, - but currently, they are just run-on sentences, so we should convert them, i.e.,

https://experienceleague.adobe.com/docs/commerce-operations/tools/observation-for-adobe-commerce/bots.html?lang=en#total-bot-traffic-by-bot-name%2Fip-address-during-selected-time-period-how-to-block-bot-traffic-on-fastly-level-or-manage-bots-through-your-robots.txt-file-best-practices-for-adobe-commerce-robots.txt

```
Total Bot Traffic by Bot name/IP address during selected time period How to block bot traffic on Fastly level OR manage bots through your robots.txt file
```

For example, with the links included:

Total Bot Traffic by Bot name/IP address during selected time period[ How to block bot traffic on Fastly level ](https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/how-to/block-malicious-traffic-for-magento-commerce-on-fastly-level.html?lang=en) OR manage bots through your robots.txt file [Best practices for Adobe Commerce robots.txt](https://experienceleague.adobe.com/docs/commerce-operations/implementation-playbook/best-practices/launch/robots-txt.html?lang=en)

**Comment by Rinn22** [comment]
PR fixing this issue: https://git.corp.adobe.com/AdobeDocs/commerce-operations.en/pull/504

**Comment by hguthrie** [comment]
Closing since the noted PR addressed the issue.
