### ISSUE TITLE
Global Search is not working on this page for Firefox mac os

### ISSUE THREAD

**Issue by mr-ap-code** [AdobeDocs/commerce-operations.en#82]
Issue in ./help/release/release-notes/commerce/2-4-5.md

attached the video for evidence

https://www.awesomescreenshot.com/video/14946938?key=8e1fc60ba130c9af991f16e54eb6d79b

**Comment by jeff-matthews** [comment]
Hi @abalachandra,

That definitely looks like a bug. Thanks for letting us know. We'll get it fixed.

**Comment by jeff-matthews** [comment]
Created internal ticket (UGP-8635)

**Comment by jeff-matthews** [comment]
@abalachandra, the issue should be fixed now. I confirmed on my browser. Please re-open if you continue to have issues.

**Comment by mr-ap-code** [comment]
@jeff-matthews Thank you for letting me know. I have checked and can confirm that the issue is resolved now. I appreciate your prompt action in resolving this matter.
