### ISSUE TITLE
I can't see the option My Profile 

### ISSUE THREAD

**Issue by jpainvicta** [AdobeDocs/commerce-operations.en#83]
Issue in ./help/installation/tutorials/extensions.md

Every time that I'm trying to get the My profile the site is have some kind of issue. Please advise, this is really urgent. Thanks

**Comment by jeff-matthews** [comment]
@jpainvicta, do you see a "Sign in" button in the top nav? After you sign in, you should see an option to get to your profile.

![Screenshot 2023-02-21 at 8 56 27 AM](https://user-images.githubusercontent.com/13662379/220379649-00f26cf5-2f5b-4bef-b7b4-b26955f2d8c8.png)

**Comment by jpainvicta** [comment]
Hello Jeff,

I have this logged with the account that we used in the past to purchase the
extension but I just can see this ***@***.***):

[image: image.png]


If I login with a different account ***@***.***) I got this:
[image: image.png]


Please advise.

Thanks in advance.


Best regards,


Japhet Perez Atristain
Sr. Manager eCommerce Technology Operations
***@***.***

**Comment by jeff-matthews** [comment]
@jpainvicta, the images you reference in your last message aren't actually appearing, but think I understand now.

You're referring to "My Profile" on the https://marketplace.magento.com/ page (as described in the [docs](https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/tutorials/extensions.html?lang=en#get-the-extension-composer-name-and-version). 

This doesn't sound like an issue with the docs. I recommend opening a ticket with Marketplace Support: https://marketplacesupport.magento.com/hc/en-us.
