### ISSUE TITLE
MySQL version >= 8.0.29 is no longer compatible with Magento <= 2.4.5

### ISSUE THREAD

**Issue by diwipl** [AdobeDocs/commerce-operations.en#84]
## Topic Link

https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

## Description

The system requirements page
https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html

Mentions MySQL 8.0 being compatible.

Unfortunately, MySQL starting with version 8.0.29 is no longer compatible until Magento 2.4.6 is released.
More info here: https://github.com/magento/magento2/issues/35671

## Possible solutions

It would be good to update requirements for Magento versions <= 2.4.5 and inform that only MySQL versions >= 8.0 and <= 8.0.29 are supported.

**Comment by jeff-matthews** [comment]
Thanks for reporting @diwipl! I'll follow up with internal resources and update the table as necessary.

**Comment by jeff-matthews** [comment]
Confirmed with internal resources. I'll prepare an update for the 2.4.6 release.

**Comment by jeff-matthews** [comment]
@diwipl, is this what you were thinking? 

![Screenshot 2023-02-27 at 1 56 43 PM](https://user-images.githubusercontent.com/13662379/221682378-5bc9bd8d-1557-4a98-b1f9-4e6a3355860e.png)

**Comment by jeff-matthews** [comment]
Actually, I think this is what we want:

![Screenshot 2023-02-27 at 3 27 39 PM](https://user-images.githubusercontent.com/13662379/221689557-d4b4c8a2-336e-4b71-8120-3502b8bf47f1.png)

**Comment by jeff-matthews** [comment]
Instead, I think we're going to add an asterisk to 8.0 for 2.4.5 and earlier and then below the table we'll add a note.

**Comment by diwipl** [comment]
Hi

All of the proposed solutions look fine to me :)

**Comment by jeff-matthews** [comment]
The page was updated.

**Comment by diwipl** [comment]
Thank you very much,

In my opinion the ticket can be closed :)
