### ISSUE TITLE
Feature request - Stop GEO locate by IP AND browser language in Experience League devdocs for Magento

### ISSUE THREAD

**Issue by JesperHerrloff** [AdobeDocs/commerce-operations.en#85]
## Description

Stop choose what language I will get. Most of us professional developers reads technical documentation in English. I think there is less than 1% that enjoys reading technical documentations in their own language as most of development environments is in english.

## Expected result

To choose by my self if I want to translate the site to Swedish or other languages. 

## Benefits

The benefits is obviously that its easier to grasp the content when its in correctly english than a localized version that translates words poorly.

## Possible solutions

Stop automatic translation both by IP and browser language

## Additional information

I think i provided enough information to make it clear that a person should be in charge of what language he och she prefers.

**Comment by jeff-matthews** [comment]
This is working as designed per the Product team that manages the Experience League site and there are no plans to change it.
