### ISSUE TITLE
Elasticsearch is no longer supported on cloud after Adobe commerce 2.4.4

### ISSUE THREAD

**Issue by ikhadka** [AdobeDocs/commerce-operations.en#88]
Issue in ./help/installation/system-requirements.md

Hello Team, 

Please could you update this article to mention that Elasticsearch is only supported for on-premise customers and cloud customers need to switch to opensearch from adobe commerce version 2.4.4. Currently this article does not mention this clearly and customers are getting confused. Please see the support article on which is is stated: https://experienceleague.adobe.com/docs/commerce-knowledge-base/kb/announcements/commerce-announcements/switching-to-opensearch-for-adobe-commerce-on-cloud-2.4.4.html?lang=en

If you have any further questions please reach out to me. 

Thanks 
Ishwar

**Comment by jeff-matthews** [comment]
See https://github.com/AdobeDocs/commerce-operations.en/issues/79#issuecomment-1634319926
