### ISSUE TITLE
Magento 2.4.6 does not support MariaDB 10.6 and docs specify 10.6.

### ISSUE THREAD

**Issue by fernandogsaatva** [AdobeDocs/commerce-operations.en#94]
Issue in ./help/installation/system-requirements.md

I'm getting this message when upgrading to MariaDB 10.6 for Magento 2.4.6:
```
Current version of RDBMS is not supported. Used Version: 10.6.13-MariaDB-1:10.6.13+maria~ubu2004. Supported versions: MySQL-8, MySQL-5.7, MariaDB-(10.2-10.4) 
```

[More documentation](https://experienceleague.adobe.com/docs/commerce-operations/release/notes/magento-open-source/2-4-6.html#:~:text=MariaDB%2010.6%20(LTS%20version).%20This%20release%20is%20still%20compatible%20with%20MariaDB%2010.4%2C%20but%20we%20recommend%20upgrading%20to%20MariaDB%2010.6)

**Comment by hguthrie** [comment]
@fernandogsaatva  I don't know why you have this error.
I am marking this as not a Docs issue. You can reopen or create a new issue If you find more out more information and can verify that this is a docs issue.
