### ISSUE TITLE
SWAT agent install script uses wrong domain

### ISSUE THREAD

**Issue by adriansanta** [AdobeDocs/commerce-operations.en#95]
Issue in ./help/tools/site-wide-analysis-tool/installation.md

The script mentioned in the scripted install is using the outdated domain updater.swat.magento.com (line 12), which is not working (https://updater.swat.magento.com/launcher/launcher.linux-amd64.tar.gz), instead of the new one - updater.supportinsights.adobe.com.

https://raw.githubusercontent.com/magento-swat/install-agent-helpers/main/install.sh

Thank you for updating this.

**Comment by jeff-matthews** [comment]
Thanks for letting us know @adriansanta. Technically, this is a code issue and not a docs issue. Please open an issue in the [magento-swat/install-agent-helpers](https://github.com/magento-swat/install-agent-helpers) repo.

Cc: @yvoronoy

**Comment by jeff-matthews** [comment]
Actually, it looks like there's already a Pr in that repo to update it: https://github.com/magento-swat/install-agent-helpers/pull/25

**Comment by adriansanta** [comment]
i see, thanks for the update, i must have missed it! regards
