### ISSUE TITLE
Cloud Commerce Does Not Have Anti-Virus

### ISSUE THREAD

**Issue by BarnyShergold** [AdobeDocs/commerce-operations.en#96]
Issue in ./help/implementation-playbook/infrastructure/cloud/managed-services.md

The first image indicates that Cloud Commerce has Anti-Virus - it does not. It is not part of the architecture, this should be removed

**Comment by hguthrie** [comment]
Yeah, and that graphic is very weird. Maybe we can create a new one or make it a list.

**Comment by hguthrie** [comment]
Done; should publish soon.
