### ISSUE TITLE
Lack of information about pcntl extension

### ISSUE THREAD

**Issue by isitnikov** [AdobeDocs/commerce-operations.en#99]
Issue in ./help/configuration/cli/manage-indexers.md

There is no information about requirements for Parallel Reindex functionality.
It requires **pcntl** (Process Control) extension on PHP (https://www.php.net/manual/en/pcntl.installation.php)

Official PHP documentation says:

> Process Control support in PHP is not enabled by default. You have to compile the CGI or CLI version of PHP with --enable-pcntl configuration option when compiling PHP to enable Process Control support.

**Comment by isitnikov** [comment]
Also I see that https://experienceleague.adobe.com/docs/commerce-operations/installation-guide/system-requirements.html?lang=en should be updated as well, because we don't have requirement for **pcntl**. It should be at least optionally with explanation that it's needed for Parallel Reindex.

**Comment by hguthrie** [comment]
I don't see it listed in System Requirements for on-prem as a requirement. For Cloud it is in the default installed list, but that doesn't imply that it is required.
But we have some information in the Configuration guide: https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/manage-indexers.html?lang=en#reindexing-in-parallel-mode
Is this the kind of information you seek?

**Comment by isitnikov** [comment]
Hello @hguthrie 

I mean this is a problem, that we don't mention **pcntl** extension as required or at least optional. Merchant who wants to use parallel reindex will not able to use it and documentation says nothing about pcntl extension unfortunately.

**Comment by isitnikov** [comment]
https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/manage-indexers.html?lang=en#reindexing-in-parallel-mode doesn't contain any mentions of **pcntl** extension.

**Comment by hguthrie** [comment]
Okay, got it. We can certainly look at how this can be improved. Thanks for pointing it out.

**Comment by hostep** [comment]
For what it's worth, the `pcntl` extension is also necessary for parallel compilation of static assets (the `--job` flag in the `bin/magento setup:static-content:deploy` command). It has an explicit check for this in [the codebase](https://github.com/magento/magento2/blob/0a834cce01c3d924d450c9a71123d9ac6de68b62/app/code/Magento/Deploy/Process/Queue.php#L302-L305).

So I think https://experienceleague.adobe.com/docs/commerce-operations/configuration-guide/cli/static-view/static-view-file-deployment.html?lang=en also needs to be updated to mention this explicitly.

**Comment by isitnikov** [comment]
Good catch @hostep ! Totally agree.

**Comment by jeff-matthews** [comment]
@adobe export issue to Jira project COMDOX as Story

**Comment by jeff-matthews** [comment]
Addressed in https://github.com/AdobeDocs/commerce-operations.en/commit/b78c3b2d567418cd8867449515e4c177cd1f7938
